app = "mac-exe-converter"
primary_region = "lhr"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = [ "app" ]
timeout = 0

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
